---
openjdk:
- version: "1.6"
  full: openjdk6-u25-heroku-temaki.tar.gz
  jre: openjdk6-jre-u25.tar.gz
- version: "1.7"
  full: openjdk7-u7-heroku-temaki-b30.tar.gz
  jre: openjdk7-jre-u7-b30.tar.gz
- version: "1.8"
  full: openjdk8-lambda-preview.tar.gz
  jre: openjdk8-jre-lambda-preview.tar.gz